apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: catalog-api # must much from ./kustomization.yaml -> images[0].name
        imagePullPolicy: Always 
        ports:
          - containerPort: 8000
        env:
        - name: ROCKET_PORT
          value: "8000"
        - name: ROCKET_ADDRESS
          value: "0.0.0.0"
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: catalog-api
              key: env
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: catalog-api
              key: base.path
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: catalog-api
              key: db.url
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: catalog-api
              key: auth.url
        - name: AUTH_AUTHORITY
          valueFrom:
            configMapKeyRef:
              name: catalog-api
              key: auth.authority
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 3
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
